# Generated by Django 2.2.5 on 2020-08-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/django-blog-c1e8b.appspot.com/o/jokllpaper-hd-1080p.jpg?alt=media&token=366158cf-76a0-41fe-9d9b-e82c16fb3a46'),
        ),
    ]
