# Generated by Django 2.2.5 on 2020-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200816_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
